name: MyQ
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  env_get: ^1.0.0
  myq: ^1.0.0
  debug: ^1.0.0
  modus_mqtt:
    path: ../pkg/modus_mqtt
  hostbase:
    path: ../pkg/hostbase
#  path: ^1.7.0

#dev_dependencies:
#  pedantic: ^1.9.0
