name: weather_microservice
description: RoboDomo microservice to poll for weather and publish info to MQTT
version: 1.0.0
homepage: https://github.com/ModusLabs/dart-samples/RoboDomo/weather-microservice

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  dio: ^4.0.0
  debug: ^1.0.0
  # env:
  #   path: ../pkg/env
  modus_mqtt:
    path: ../pkg/modus_mqtt
  hostbase:
    path: ../pkg/hostbase
