name: bravia
description: A Dart interface to Sony Bravia TVs (control and monitor)
version: 1.0.2
homepage: https://github.com/ModusLabs/dart-samples/RoboDomo/pkg/bravia

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  env_get: ^1.0.0
  debug: ^1.0.0
  modus_json: ^1.0.0
  statefulemitter: ^1.0.2
#  statefulemitter:
#    path: ../statefulemitter
  dio: ^4.0.0

dev_dependencies:
  pedantic: ^1.11.0
#  test: ^1.17.2
