name: myq
description: MyQ class (control MyQ garage doors and monitor sensors)
version: 1.0.0
homepage: https://github.com/ModusLabs/RoboDomo-mono

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dio: ^4.0.0
  crypto: ^3.0.1
  ansicolor: ^2.0.1
  debug: ^1.0.0
  statefulemitter: ^1.0.0
  modus_json: ^1.0.0
#  path: ^1.7.0

#dev_dependencies:
#  pedantic: ^1.11.0
