name: debug
description: >-
  This is something of a clone/work-alike of the JavaScript debug package by TJ Holowaychuck at https://github.com/visionmedia/debug.
  Use:
    import 'package:debug/debug.dart';
    final debug = Debug('any_key_you_like')

    ...
    debug('any string you like, as if you called print()');

  The DEBUG environment variable is checked to see if anything should be printed.  You can specify multiple keys in DEBUG by separating them with semicolon.  The * key matches ALL keys for all debugs.

  This package was developed as part of a port of Modus Create's IoT platform, RoboDomo from JavaScript to Dart and Flutter.  The original can be found at https://github.com/RoboDomo.

version: 1.0.0

homepage: https://github.com/ModusLabs/RoboDomo-mono

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dart_console: ^1.0.0
  env_get: ^1.0.0
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.11.0
#  test: ^1.17.2
