name: modus_mqtt
description: MQTT class
version: 1.0.0
repository: https://github.com/ModusLabs/RoboDomo-mono

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  debug: ^1.0.0
  statefulemitter: ^1.0.2
  modus_json: ^1.0.0
  mqtt_client: ^9.3.1
  ansicolor: ^2.0.1

